# Generated by Django 4.2.9 on 2024-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.IntegerField(null=True, verbose_name='Phone')),
                ('check_in', models.DateField(verbose_name='Check In')),
                ('checkout', models.DateField(verbose_name='Check Out')),
                ('room_type', models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Executive Suite', 'Executive Suite'), ('Super Deluxe', 'Super Deluxe')], max_length=25, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Executive Suite', 'Executive Suite'), ('Super Deluxe', 'Super Deluxe')], max_length=25, verbose_name='Type')),
                ('number', models.IntegerField(null=True, verbose_name='Number')),
                ('floor', models.IntegerField(null=True, verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
                'ordering': ('number',),
            },
        ),
    ]
