# Generated by Django 4.2.9 on 2024-02-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='checkout',
            new_name='check_out',
        ),
        migrations.AddField(
            model_name='room',
            name='occupied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='bookings'),
        ),
    ]
