# Generated by Django 4.2.9 on 2024-02-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_checkout_booking_check_out_room_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone', models.IntegerField(null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'db_table': 'staff',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxValueValidator(10)], verbose_name='Number'),
        ),
    ]
