# Generated by Django 4.2.9 on 2024-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_staff_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Executive', 'Executive'), ('Staff', 'Staff'), ('Cook', 'Cook')], max_length=25, null=True, verbose_name='Type'),
        ),
    ]
