# Generated by Django 4.2.9 on 2024-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Executive', 'Executive'), ('Staff', 'Staff'), ('Cook', 'Cook')], default='Staff', max_length=25, verbose_name='Type'),
        ),
    ]
