# Generated by Django 4.2.9 on 2024-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media/', verbose_name='Photo'),
        ),
    ]
