# Generated by Django 4.2.9 on 2024-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_room_number_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult',
            field=models.IntegerField(null=True, verbose_name='Adult'),
        ),
        migrations.AddField(
            model_name='booking',
            name='child',
            field=models.IntegerField(null=True, verbose_name='Child'),
        ),
    ]
